export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const SCHOOL_FOUND = "SCHOOL_FOUND";
export const SCHOOL_NOT_FOUND = "SCHOOL_NOT_FOUND";
